(defun pares_e_impares (vet &aux lista)
  (setq lista '())
  (setq val1 '())
  (setq val2 '())
  (dolist (i vet)                          
    (when (equal (mod i 2) 0)              
      (push i val1))
    (when (equal (mod i 2) 1)         
      (push i val2))
  )
  (setq lista (cons (nreverse val2) lista))
  (setq lista (cons (nreverse val1) lista))
  (nreverse lista)
)